# Generated by Django 5.2.9 on 2025-12-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsiReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(db_column='의뢰번호', max_length=45)),
                ('receipt_id', models.CharField(blank=True, db_column='접수번호', max_length=45, null=True)),
                ('receipt_date', models.CharField(blank=True, db_column='접수일시', max_length=45, null=True)),
                ('status', models.CharField(db_column='진행상태', max_length=45)),
                ('project', models.CharField(db_column='사업명', max_length=100)),
                ('client', models.CharField(db_column='의뢰기관명', max_length=100)),
                ('sampler', models.CharField(blank=True, db_column='채취자', max_length=45, null=True)),
                ('seal', models.CharField(blank=True, db_column='봉인명', max_length=100, null=True)),
                ('processor', models.CharField(blank=True, db_column='처리자', max_length=45, null=True)),
                ('sales_type', models.CharField(db_column='영업구분', max_length=45)),
                ('manager', models.CharField(blank=True, db_column='담당자', max_length=45, null=True)),
                ('confirm', models.CharField(blank=True, db_column='확인', max_length=45, null=True)),
                ('amount', models.CharField(blank=True, db_column='시료량', max_length=100, null=True)),
                ('category', models.CharField(db_column='구분', max_length=45)),
                ('site_manager', models.CharField(blank=True, db_column='현장담당자', max_length=100, null=True)),
                ('assign_date', models.CharField(blank=True, db_column='배정일자', max_length=45, null=True)),
                ('assign_status', models.CharField(blank=True, db_column='배정현황', max_length=45, null=True)),
                ('unapproved', models.CharField(blank=True, db_column='미인정', max_length=45, null=True)),
            ],
            options={
                'db_table': 'csi_receipts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OuterreceiptNew',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('receiptcode', models.CharField(blank=True, db_column='receiptCode', max_length=10, null=True)),
                ('rqcode', models.CharField(blank=True, db_column='rqCode', max_length=14, null=True)),
                ('accode', models.CharField(blank=True, db_column='acCode', max_length=14, null=True)),
                ('rq_no', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picker_name', models.CharField(blank=True, max_length=50, null=True)),
                ('seal_name', models.TextField(blank=True, null=True)),
                ('specific_user', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'OuterReceipt',
                'managed': False,
            },
        ),
    ]
