# Generated by Django 5.2.9 on 2026-01-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='연락처')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('memo', models.TextField(blank=True, verbose_name='담당자 특징')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='MSSQL 매칭 사업명')),
                ('company', models.CharField(max_length=100, verbose_name='건설사/기관')),
                ('request_code', models.CharField(blank=True, max_length=50, verbose_name='의뢰번호')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='board.client')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='상담내용')),
                ('todo_type', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='예약기한')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='board.clientproject')),
            ],
        ),
    ]
