# Generated by Django 5.2.9 on 2026-01-21 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_client_clientproject_consultationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='client',
        ),
        migrations.RemoveField(
            model_name='consultationlog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='company',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='request_code',
        ),
        migrations.AddField(
            model_name='clientproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientproject',
            name='is_linked',
            field=models.BooleanField(default=False, verbose_name='MSSQL 연결 여부'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='reg_company',
            field=models.CharField(default='', max_length=100, verbose_name='의뢰기관명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientproject',
            name='reg_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='reg_name',
            field=models.CharField(default='', max_length=50, verbose_name='담당자 성함'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientproject',
            name='reg_phone',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='연락처'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientproject',
            name='reg_project_name',
            field=models.CharField(default='', max_length=200, verbose_name='MSSQL 사업명'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConsultMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='상담내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='board.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('task_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.clientproject')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ConsultationLog',
        ),
    ]
